const specialtyDoctor = [
    { value: 0 , label: 'NENHUMA' },
    { value: 1 , label: 'ACUPUNTURA' },
    { value: 2 , label: 'ADMINISTRAÇÃO EM SAÚDE' },
    { value: 3 , label: 'ADMINISTRAÇÃO HOSPITALAR' },
    { value: 4 , label: 'ALERGIA E IMUNOLOGIA' },
    { value: 5 , label: 'ALERGIA E IMUNOPATOLOGIA' },
    { value: 6 , label: 'ANATOMIA PATOLÓGICA' },
    { value: 7 , label: 'ANESTESIOLOGIA' },
    { value: 8 , label: 'ANGIOLOGIA' },
    { value: 9 , label: 'ANGIOLOGIA E CIRURGIA VASCULAR' },
    { value: 10 , label: 'BRONCOESOFAGOLOGIA' },
    { value: 11 , label: 'CANCEROLOGIA' },
    { value: 12 , label: 'CANCEROLOGIA/CANCEROLOGIA CIRÚRGICA' },
    { value: 13 , label: 'CANCEROLOGIA/CANCEROLOGIA PEDIÁTRICA' },
    { value: 14 , label: 'CARDIOLOGIA' },
    { value: 15 , label: 'CIRURGIA CARDIOVASCULAR' },
    { value: 16 , label: 'CIRURGIA DA MÃO' },
    { value: 17 , label: 'CIRURGIA DE CABEÇA E PESCOÇO' },
    { value: 18 , label: 'CIRURGIA DIGESTIVA' },
    { value: 19 , label: 'CIRURGIA DO APARELHO DIGESTIVO' },
    { value: 20 , label: 'CIRURGIA DO TRAUMA' },
    { value: 21 , label: 'CIRURGIA GASTROENTEROLÓGICA' },
    { value: 22 , label: 'CIRURGIA GERAL' },
    { value: 23 , label: 'CIRURGIA ONCOLÓGICA' },
    { value: 24 , label: 'CIRURGIA PEDIÁTRICA' },
    { value: 25 , label: 'CIRURGIA PLÁSTICA' },
    { value: 26 , label: 'CIRURGIA TORÁCICA' },
    { value: 27 , label: 'CIRURGIA TORÁXICA' },
    { value: 28 , label: 'CIRURGIA VASCULAR' },
    { value: 29 , label: 'CIRURGIA VASCULAR PERIFÉRICA' },
    { value: 30 , label: 'CITOPATOLOGIA' },
    { value: 31 , label: 'CLÍNICA MÉDICA' },
    { value: 32 , label: 'COLOPROCTOLOGIA' },
    { value: 33 , label: 'DENSITOMETRIA ÓSSEA' },
    { value: 34 , label: 'DERMATOLOGIA' },
    { value: 35 , label: 'DIAGNÓSTICO POR IMAGEM' },
    { value: 36 , label: 'DOENÇAS INFECCIOSAS E PARASITÁRIAS' },
    { value: 37 , label: 'ELETROENCEFALOGRAFIA' },
    { value: 38 , label: 'ENDOCRINOLOGIA' },
    { value: 39 , label: 'ENDOCRINOLOGIA E METABOLOGIA' },
    { value: 40 , label: 'ENDOSCOPIA' },
    { value: 41 , label: 'ENDOSCOPIA DIGESTIVA' },
    { value: 42 , label: 'ENDOSCOPIA PERORAL' },
    { value: 43 , label: 'ENDOSCOPIA PERORAL VIAS AÉREAS' },
    { value: 44 , label: 'FISIATRIA' },
    { value: 45 , label: 'FONIATRIA' },
    { value: 46 , label: 'GASTROENTEROLOGIA' },
    { value: 47 , label: 'GENÉTICA CLÍNICA' },
    { value: 48 , label: 'GENÉTICA MÉDICA' },
    { value: 49 , label: 'GERIATRIA' },
    { value: 50 , label: 'GERIATRIA E GERONTOLOGIA' },
    { value: 51 , label: 'GINECOLOGIA' },
    { value: 52 , label: 'GINECOLOGIA E OBSTETRÍCIA' },
    { value: 53 , label: 'HANSENOLOGIA' },
    { value: 54 , label: 'HEMATOLOGIA' },
    { value: 55 , label: 'HEMATOLOGIA E HEMOTERAPIA' },
    { value: 56 , label: 'HEMOTERAPIA' },
    { value: 57 , label: 'HEPATOLOGIA' },
    { value: 58 , label: 'HOMEOPATIA' },
    { value: 59 , label: 'IMUNOLOGIA CLÍNICA' },
    { value: 60 , label: 'INFECTOLOGIA' },
    { value: 61 , label: 'INFORMÁTICA MÉDICA' },
    { value: 62 , label: 'MASTOLOGIA' },
    { value: 63 , label: 'MEDICINA DE EMERGÊNCIA' },
    { value: 64 , label: 'MEDICINA DE FAMÍLIA E COMUNIDADE' },
    { value: 65 , label: 'MEDICINA DE TRÁFEGO' },
    { value: 66 , label: 'MEDICINA DO ADOLESCENTE' },
    { value: 67 , label: 'MEDICINA DO ESPORTE' },
    { value: 68 , label: 'MEDICINA DO TRABALHO' },
    { value: 69 , label: 'MEDICINA ESPORTIVA' },
    { value: 70 , label: 'MEDICINA FÍSICA E REABILITAÇÃO' },
    { value: 71 , label: 'MEDICINA GERAL COMUNITÁRIA' },
    { value: 72 , label: 'MEDICINA INTENSIVA' },
    { value: 73 , label: 'MEDICINA INTERNA OU CLÍNICA MÉDICA' },
    { value: 74 , label: 'MEDICINA LEGAL' },
    { value: 75 , label: 'MEDICINA LEGAL E PERÍCIA MÉDICA' },
    { value: 76 , label: 'MEDICINA NUCLEAR' },
    { value: 77 , label: 'MEDICINA PREVENTIVA E SOCIAL' },
    { value: 78 , label: 'MEDICINA SANITÁRIA' },
    { value: 79 , label: 'NEFROLOGIA' },
    { value: 80 , label: 'NEUROCIRURGIA' },
    { value: 81 , label: 'NEUROFISIOLOGIA CLÍNICA' },
    { value: 82 , label: 'NEUROLOGIA' },
    { value: 83 , label: 'NEUROLOGIA PEDIÁTRICA' },
    { value: 84 , label: 'NEUROPEDIATRIA' },
    { value: 85 , label: 'NUTRIÇÃO PARENTERAL E ENTERAL' },
    { value: 86 , label: 'NUTROLOGIA' },
    { value: 87 , label: 'OBSTETRÍCIA' },
    { value: 88 , label: 'OFTALMOLOGIA' },
    { value: 89 , label: 'ONCOLOGIA' },
    { value: 90 , label: 'ONCOLOGIA CLÍNICA' },
    { value: 91 , label: 'ORTOPEDIA E TRAUMATOLOGIA' },
    { value: 92 , label: 'OTORRINOLARINGOLOGIA' },
    { value: 93 , label: 'PATOLOGIA CLÍNICA' },
    { value: 94 , label: 'PATOLOGIA CLÍNICA/MEDICINA LABORATORIAL' },
    { value: 95 , label: 'PEDIATRIA' },
    { value: 96 , label: 'PNEUMOLOGIA' },
    { value: 97 , label: 'PNEUMOLOGIA E TISIOLOGIA' },
    { value: 98 , label: 'PROCTOLOGIA' },
    { value: 99 , label: 'PSIQUIATRIA' },
    { value: 100 , label: 'PSIQUIATRIA INFANTIL' },
    { value: 101 , label: 'RADIODIAGNÓSTICO' },
    { value: 102 , label: 'RADIOLOGIA' },
    { value: 103 , label: 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM' },
    { value: 104 , label: 'RADIOTERAPIA' },
    { value: 105 , label: 'REUMATOLOGIA' },
    { value: 106 , label: 'SEXOLOGIA' },
    { value: 107 , label: 'TERAPIA INTENSIVA' },
    { value: 108 , label: 'TERAPIA INTENSIVA PEDIÁTRICA' },
    { value: 109 , label: 'TISIOLOGIA' },
    { value: 110 , label: 'TOCO-GINECOLOGIA' },
    { value: 111 , label: 'ULTRASSONOGRAFIA' },
    { value: 112 , label: 'ULTRASSONOGRAFIA EM GINECOLOGIA E OBSTETRÍCIA' },
    { value: 113 , label: 'ULTRASSONOGRAFIA GERAL' },
    { value: 114 , label: 'UROLOGIA' }
];
  
  export default { specialtyDoctor };